export enum ModalsEnum {
    CREATE_EVENT_MODAL_NAME = 'Create New Event ✏️',
    EDIT_EVENT_MODAL_NAME = 'Edit Event ID: #',
    CREATE_EVENT = 'create-event',
    EDIT_EVENT = 'edit-event',
    EVENT_NAME_INPUT_LABEL = 'Enter Event Name *',
    EVENT_NAME_INPUT_LABEL_DEFAULT = 'enter the event name here',
    EVENT_NAME_INPUT = 'event-name',
    EVENT_NAME_BLOCK = 'event-name-block',
    EVENT_DESCRIPTION_BLOCK = 'event-description-block',
    EVENT_DESCRIPTION_INPUT_LABEL = 'Enter Event Description',
    EVENT_DESCRIPTION_INPUT_LABEL_DEFAULT = 'enter the event description here',
    EVENT_DESCRIPTION_INPUT = 'event-description',
    EVENT_START_DATE_BLOCK = 'event-start-date-block',
    EVENT_START_DATE_INPUT_LABEL = ' Enter Start Date *',
    EVENT_START_DATE_INPUT = 'event-start-date',
    EVENT_DUE_DATE_BLOCK = 'event-due-date-block',
    EVENT_DUE_DATE_INPUT_LABEL = ' Enter Due Date *',
    EVENT_DUE_DATE_INPUT = 'event-due-date',
    GET_EVENTS_MODAL_NAME = 'Get Events ',
    GET_EVENTS_SUBMIT_BUTTON_LABEL = 'Get Events',
    GET_EVENTS = 'get-events',
    EVENT_LIMIT_INPUT_LABEL = 'Enter number of events to retrieve (max is 100)',
    EVENT_LIMIT_INPUT_LABEL_DEFAULT = '10',
    EVENT_LIMIT_INPUT = 'event-limit',
    EVENT_LIMIT_BLOCK = 'event-limit-block',
    OPTIONAL_PARAMETERS_LABEL = 'Optional Parameters (click to view/change)',
    EVENT_ID_BLOCK = 'event-id-block',
    EVENT_ID_LABEL = 'Enter Event ID:',
    EVENT_ID_INPUT = 'event-id',
    EVENT_ID_PLACEHOLDER = 'enter event id here'

}
